/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

import org.junit.Test;

public class AppTest {
    @Test public void appHasAGreeting() throws Exception {
        System.out.println("Test A");
        App.main(new String[5]);
    }

    @Test public void testNeg() throws Exception {
        System.out.println("Test B");
        try{
            App.main(new String[5]);
        }catch(Exception e){ throw e;}
        //fail("Tu es nul");
    }
}
